### ISSUE TITLE
Support for coffee-script source maps

### ISSUE THREAD

**Issue by MaksJS** [adunkman/connect-assets#179]
Hi everyone, great to see that this module isn't dead already :)
That would great if you could generate source maps with coffee-script files at compile. It's now available with CS 1.6. Maybe it's more a snockets enhancement ?

**Comment by domachine** [comment]
Any news in this?

**Comment by domachine** [comment]
Seems that mincer now supports that [feature](http://nodeca.github.io/mincer/#Manifest.prototype.compile). This is currently the only reason holding me back to use this.

**Comment by siboulet** [comment]
Any updated on this? How to enable generating source maps in connect-assets? Seems Mincer now supports it, as mentioned by @domachine. Without source maps debugging minified assets is impossible.

**Comment by adunkman** [comment]
I haven’t made the time to make it happen in connect-assets, but pull requests are always welcome!
