### ISSUE TITLE
Bower + Connect Assets v3

### ISSUE THREAD

**Issue by sameersegal** [adunkman/connect-assets#241]
Hi, I have tried to read the various issues regarding ```asseturl``` but I haven't gotten any where. I am using bower to manage my dependencies like bootstrap and ace editor which have a local references to their assets images, other js files etc e.g. ```background: url('../fonts/..')```. 

I switched from v2 to v3 hoping for a solution. I have tried placing ```asseturl``` in my less files etc but the urls are not getting modified. However this can't be the real solution when you are using bower, requirejs because the dependencies are downloaded dynamically before starting the server.

Thanks for the help in advance

**Comment by eruanntion** [comment]
Hi!

What would be proper syntax for scss files?

**Comment by blakevanlan** [comment]
Closing this out. Sounds like it's no longer an issue now that connect-assets depends on mincer.
