### ISSUE TITLE
404 When attempting to render javascript in production

### ISSUE THREAD

**Issue by adamkuipers** [adunkman/connect-assets#242]
We're using connect-assets 2.5.5 and we're getting intermittent issues with the compilation of our coffee-script files. It seems that the jade-views don't wait for the javascript to compile.

I think this may happen at application startup and so whenever Heroku decides to move our app to a new dyno our site won't render properly for about a minute. I understand that there is no way to have a pre-compilation step in a production environment in the 2.x series but do you know why the jade view wouldn't wait for the file to fully compile?

**Comment by adunkman** [comment]
Closing — there’s not enough details on this issue to confirm any sort of bug. Feel free to open a new issue with more details should this issue present itself again!
