### ISSUE TITLE
Can't find images

### ISSUE THREAD

**Issue by doomhz** [adunkman/connect-assets#244]
I'm using connect-assets for a while but I didn't use the images cache functionality for a while. Is it still available in version 2.x ?
So, basically I should drop them in the /assets/img folder and connect-assets will pick them up automatically, right?
Doesn't seem to work for me... Should I specify some configuration for it?

Styles and script concatenation and compression seem to work great so far, using it for more than 3 years already. Great job!

**Comment by nmalacarne** [comment]
You can add your image path to connect-assets via the path config option, e.g.

```
...

var assets = require('connect-assets');

app.use(assets({
  path: [
    'assets/css',
    'assets/js',
    'assets/img'
  ] 
}));
```
Then, in your jade, you can utilize connect-assets assetPath(), e.g.

```
img(src="#{assetPath('my-image.png')}") //- will give you 'assets/img/my-image.png'

**Comment by adunkman** [comment]
Yep, I anticipate #300 holds your answer. Thanks @nmalacarne!
