### ISSUE TITLE
Add support for autoprefixer

### ISSUE THREAD

**Issue by bjmiller** [adunkman/connect-assets#248]
Mincer supports autoprefixer out of the box as a processor.  Can we include that seamlessly, so it runs after converting from LESS/Stylus, and before minification?

**Comment by adunkman** [comment]
You can now pass a second argument to the function returned by `require("connect-assets")` to specify custom configuration of Mincer as connect-assets is starting up — custom configuration, like turning on autoprefixer. 

1. You’ll need the `autoprefixer-core` module.
2. Enable autoprefixer within the Mincer environment: 

   ```javascript
  app.use(require("connect-assets")(options, function (instance) {
    instance.environment.enable("autoprefixer");
  }));
  ```
