### ISSUE TITLE
possible mincer <-> autoprefixer problem

### ISSUE THREAD

**Issue by brumm** [adunkman/connect-assets#265]
hey,

it's possible to use autoprefixer in mincer by installing and enabling it:
`connectAssets.environment.enable "autoprefixer"`, see https://github.com/ai/autoprefixer#mincer

Unfortunately, after enabling it the request to my .css file 404s. 
Commenting out the line fixes it.

**Comment by adunkman** [comment]
Please try enabling autoprefixer as described in #248 — I believe it will fix the above problems.
