### ISSUE TITLE
Path error when manifest exists and compile false

### ISSUE THREAD

**Issue by denneralex** [adunkman/connect-assets#270]
Hi. I'm using a CDN to serve my files, so I'm trying to compile them with connect-assests CLI and use only the manifest.
My express config for connect-assets looks like this:
app.use(assets({servePath: 'http://mycdn.com', compile: false, buildDir: 'myBuiltAssetsFolder'}));

Using this I get an error on the following line of the helper function:
var path = servePath + "/" + asset.logicalPath;

And thats because asset is initialized this way:
if (!instance.options.compile) {
      asset = instance.manifest.assets[path];
}

The manifest.assets objs don't have the property logicalPath.
Am I missing something?Is there any other way I should do that?

**Comment by sebastianhoitz** [comment]
I still had problems with this and not using a CDN. See my current PR: #302
