### ISSUE TITLE
stuck in 4.0.0, ok in 3.0.2

### ISSUE THREAD

**Issue by devenv** [adunkman/connect-assets#280]
I know that the only difference is dropping node 0.8 support, but I'm in 0.10.32 and when using version 4.0.0 and up it's just stuck on app.use(), works for 3.0.2.
Most likely some dependency issue, I can provide more info if needed, not sure what though...

**Comment by nickyhajal** [comment]
Did you resolve this? I'm experiencing the same issue.

**Comment by devenv** [comment]
Nope

**Comment by blakevanlan** [comment]
Is this still an issue? I haven't seen it myself.
