### ISSUE TITLE
traversing to parent directory doesn't work in js file?

### ISSUE THREAD

**Issue by israelidanny** [adunkman/connect-assets#287]
I'm trying to do this:
`//= require ../lib/bootstrap.min`

And it doesn't seem to work. I get a file not found error.

This, however, would work just fine:
`//= require lib/bootstrap.min`

**Comment by chrisvdb** [comment]
I'm having the same issue... my application is based on hackathon-starter which sets connect-assets as follows:

paths: [path.join(__dirname, 'public/css'), path.join(__dirname, 'public/js')]

Paths is hence set with absolute directories, no relative. I would like to access another directory (node_modules) at the same level as public by doing:

 //= require ../../node_modules/some_dir/some_file

I get file not found. Is ".." not supported?

https://github.com/sahat/hackathon-starter/issues/298#issuecomment-122694480

**Comment by adunkman** [comment]
`..` is supported, but you cannot traverse outside of the root directory of `paths` — for example, if you have a directory structure like this:

```
my-project
┣ assets
┃ ┣ css
┃ ┗ js
┗ node_modules
```

And your `paths` configuration is the default (repeated here for clarity): 

```javascript
app.use(require("connect-assets")({
  paths: ["assets/js", "assets/css"]
}));
```

In this configuration, you cannot access anything inside of `node_modules` — since it would require traversing two levels higher than the root directories specified in `paths`.

**Comment by chrisvdb** [comment]
I still do not get it to work properly...

My directory structure is:

```
/home/chrisvdb/Dropbox/project
┣ public
┃ ┣ css
┃ ┗ js
┗ node_modules
```

I initialize connect-assets with the following line:

```
app.use(connectAssets({
  paths: [path.join(__dirname, 'public/css'), path.join(__dirname, 'public/js')]
}));
```

The path is absolute as

```
console.log([path.join(__dirname, 'public/css'), path.join(__dirname, 'public/js')]);
```

yields

```
[ '/home/chrisvdb/Dropbox/project/Code/public/css',
  '/home/chrisvdb/Dropbox/project/Code/public/js' ]
```

But still using **//= require ../../node_modules/async/lib/async** in **/home/chrisvdb/Dropbox/project/public/js/application.js** does not seem to work. A workaround is using a symlink in **/home/chrisvdb/Dropbox/project/public/js** to **../../node_modules**, but this is of course not really elegant.

**Comment by adunkman** [comment]
Hey @chrisvdb, I think we’re talking past each other. Sorry!

In your example, you can’t access anything outside of your configured paths:

```javascript
[ '/home/chrisvdb/Dropbox/project/Code/public/css',
  '/home/chrisvdb/Dropbox/project/Code/public/js' ]
```

Your `node_modules` folder is indeed outside of those paths. 

If I were you, I’d add your `node_modules` folder to your paths:

```javascript
app.use(connectAssets({
  paths: [
    path.join(__dirname, 'public/css'), 
    path.join(__dirname, 'public/js'),
    path.join(__dirname, 'node_modules')
  ]
}));
```

Then, in `/home/chrisvdb/Dropbox/project/public/js/application.js`: 

```javascript
//= require async/lib/async
```

Does that make sense?

**Comment by chrisvdb** [comment]
Yes, that makes sense... tried it and it works like a charm! Thanks a lot for your help!
