### ISSUE TITLE
Hash suffix as an option

### ISSUE THREAD

**Issue by aug-riedinger** [adunkman/connect-assets#290]
I understand the power of the hash in production to make sure there are no cache issues, but why adding it in dev environment? 

Unless I am wrong, Sprocket doesn't add it. And it adds some confusion when using chrome webinspector.

It would be nice to have it as an option, that would be defaulted to `hashSuffix: false` in dev and `hashSuffix: true` in prod.

**Comment by adunkman** [comment]
Continued discussion on #292 (now merged).
