### ISSUE TITLE
Is possible to get just url adress of specific javascript loaded with //= require paypal-button.min ?

### ISSUE THREAD

**Issue by makromat** [adunkman/connect-assets#291]
Hello Guys,

I just trying to setup paypal buttons where is neccessary has link like src="paypal-button.min.js?merchant=YOUR_MERCHANT_ID". I'm using as templates http://ectjs.com/. So then in ect template I have <%- @js('application'); %> and javascripts are loaded. But I don't know how to get url adress of specifically javascript without any tags and anything else...

Thank you!!

**Comment by adunkman** [comment]
It sounds like you’d like the URL to the asset itself, without the wrapping `<script>` tag. 

[As mentioned in the README](https://github.com/adunkman/connect-assets#markup-functions), just use the assetPath helper: `<%- @assetPath('application'); %>`.
