### ISSUE TITLE
Namespacing your assets to specific bundles

### ISSUE THREAD

**Issue by Passenger-Inspired** [adunkman/connect-assets#294]
Is it possible to have namspacing of assets so bundling can be done based on namspace?

For example, I may have 10 scripts which are used site wide which are bundled to main.js, but for the admin section, their is an extra 5 scripts which I would bundle into admin.js, because bundling into main would be unnecessary due to it only being needed for admin users.

Ben

**Comment by adunkman** [comment]
Yes, you can do that. Just create two files, named `main.js` and `admin.js`, and reference the files you’d like included in those bundles. For example: 

**main.js:**
```javascript
//= require jquery.js
//= require my-other-files.js
```

**admin.js:**
```javascript
//= require jquery.js
//= require some-files-needed-only-in-admin-areas.js
```

Then just reference those bundles in your layouts:

```html
<!DOCTYPE html>
<html>
  <head>
    <h1>my main layout</h1>
    <%- js("main.js") %>
```

```html
<!DOCTYPE html>
<html>
  <head>
    <h1>my admin layout</h1>
    <%- js("admin.js") %>
```
