### ISSUE TITLE
Accept JSX files

### ISSUE THREAD

**Issue by aug-riedinger** [adunkman/connect-assets#303]
I'm not enough aware of how the whole thing work, but it would be really cool that it could require JSX files in development and precompile them in production!

**Comment by netsgnut** [comment]
`connect-assets` is a bridge to the [Mincer project](http://nodeca.github.io/mincer). You may want to try to use [mincer-jsx](https://www.npmjs.com/package/mincer-jsx) for that purpose.

**Comment by aug-riedinger** [comment]
Sounds good, I'll have a look at it!

**Comment by netsgnut** [comment]
Good luck! :)

**Comment by xpepermint** [comment]
+1

**Comment by netsgnut** [comment]
For the records, for those of you who want to get jsx support, try this:

```js
var Mincer = require('mincer');
require('mincer-jsx')(Mincer);
```

It will be picked up by the compiler automagically.

**Comment by adunkman** [comment]
:tada: Thanks for posting the code for posterity! :heart:
