### ISSUE TITLE
Update uglify-js to 2.4.23

### ISSUE THREAD

**Issue by deployable** [adunkman/connect-assets#308]
UglifyJS2 has had a lot of bug fix releases as well. https://github.com/mishoo/UglifyJS2/releases

**Comment by deployable** [comment]
Is it a conscious decision not to use the "~" operator for the latest minor version in the dependency definitions?

**Comment by adunkman** [comment]
Yes, I feel like when you install a particular version of `connect-assets` you should receive the same software every time.

**Comment by adunkman** [comment]
Updated in #313.
