### ISSUE TITLE
Update Mincer to 1.2.5

### ISSUE THREAD

**Issue by dapriett** [adunkman/connect-assets#310]
I would like to request Mincer get updated to the latest, 1.2.5.  Had a bug that got fixed in the latest version (https://github.com/nodeca/mincer/pull/194).  Maybe change the version to ~1.2.5 so it'll automatically pick up minor updates?

Thanks!

**Comment by dmtaub** [comment]
+1

**Comment by adunkman** [comment]
Pull requests are welcome! 

> Maybe change the version to ~1.2.5 so it'll automatically pick up minor updates?

I feel like when you install a particular version of `connect-assets` you should receive the same software every time, so I’m against any sort of relative versioning for this package. You can try to convince me otherwise, but it’s an uphill battle. :)

**Comment by adunkman** [comment]
Mincer was updated to 1.3 in #313
