### ISSUE TITLE
require dependencies build issues with version 5.0.0

### ISSUE THREAD

**Issue by dapriett** [adunkman/connect-assets#318]
I tried upgrading from version 4.8.0 to 5.0.0.  Now in my application JS file when I add requires `//= require dependency`, it's causing both a `<script>` tag to be created, as well as concating it to my application js.  I'm running in dev mode, so it should only add the `<script>` tags.  I reverted back to 4.8.0 and now I'm fine.

**Comment by adunkman** [comment]
Interesting! Thanks for the issue report @dapriett.

/cc @blakevanlan in case you saw something similar in #315.

**Comment by blakevanlan** [comment]
I didn't see this when I was adding source maps but I was able to reproduce the issue. I'll give it a look and see what's going on.

**Comment by adunkman** [comment]
Published as `v5.0.1`. Thanks for reporting the bug, @dapriett! It’s now covered by [this test](https://github.com/adunkman/connect-assets/blob/3f91690020e970f201d708c6094b174af9e2ba9d/test/serveAsset.build.js#L19-L39).

**Comment by dapriett** [comment]
Thanks for the fix @adunkman!  Just tested it, works good now.
