### ISSUE TITLE
Change repo description

### ISSUE THREAD

**Issue by aug-riedinger** [adunkman/connect-assets#321]
I find this repo highly useful and should definitely be better stared.

I small suggestion, donc describe the repo with

> A Rails 3.1-style asset pipeline for Node.js

It sounds very old-fashioned, as Rails is now 5. Go for a 

> A Rails-style asset pipeline for Node.js

it should totally do.

**Comment by adunkman** [comment]
You got it! Thanks for paying attention to the details. :heart:

**Comment by aug-riedinger** [comment]
Cool cheers :smile:
