### ISSUE TITLE
Referen file to child directory

### ISSUE THREAD

**Issue by nguyenquynhan** [adunkman/connect-assets#325]
Hi adunkman,
My directory struct as below:
public
-assets
--js
---- *.js
--css
---- *.css
--libs
---- boostrap
-------boostrap.css
-------boostrap.js

I want to referent to boostrap.js, i use: != js("libs/boostrap/boostrap.js") but it errors "not found in search path"
How must do I do it?
Thanks!

**Comment by sinoon** [comment]
I suggest you collect all js files to a same directory

**Comment by blakevanlan** [comment]
Sorry for the (long) delayed response. For anyone that stumbles upon this issue:

You should be able to use the `paths` options to specify the additional directory:
```javascript
app.use(assets({
  paths: [
    'assets/css',
    'assets/js',
    'assets/libs/'
  ]
}));
```
And then use the `!= js("boostrap/boostrap.js")` to reference the file.
