### ISSUE TITLE
Assets path helper for Less files

### ISSUE THREAD

**Issue by katgironpe** [adunkman/connect-assets#326]
I saw the example for`css.ejs` file is working but not for LESS.

Assuming this is not yet supported. I am trying to figure it out but for now, I found a workaround to get the project in production.

**Comment by blakevanlan** [comment]
Looks like Mincer should support what you are trying to do: https://github.com/nodeca/mincer#using-helpers

**Comment by katgironpe** [comment]
@blakevanlan Thanks. Checking it out. Would be great if you support it however.
