### ISSUE TITLE
Current `mincer` dependency references the deprecated `autoprefixer-core`

### ISSUE THREAD

**Issue by codynguyen** [adunkman/connect-assets#333]
Hi,

As the title says, the current `mincer@1.3.0` dependency references deprecated [`autoprefixer-core`](https://github.com/ai/autoprefixer-core). This results in project using `connect-assets` with `autoprefixer` functionality having to list the deprecated library as one of the dependencies. 

The latest `mincer@1.4.0` now references `autoprefixer` (the current official repo & module name). Please see related `mincer` [changelog](https://github.com/nodeca/mincer/blob/master/HISTORY.md#140--2015-10-24) for more information.

I already tried upgrading and fixing the 8 failed tests the upgrade causes to no avail :sob: I think it'd better be put in good hands.

Thanks!

**Comment by codynguyen** [comment]
Any updates?

**Comment by siboulet** [comment]
Any updates on this? Mincer is now at 1.4.1.

**Comment by blakevanlan** [comment]
Just published v5.2.0, which now depends on Mincer 1.4.1.
