### ISSUE TITLE
command line --compile not working

### ISSUE THREAD

**Issue by twilly86** [adunkman/connect-assets#339]
See screen shot, I'm trying to compile just my main.less file.

It's not compiling into builtAssets.

When I remove --compile it works.

Is there a way to turn on verbose logging to see what's going on in the background?

![image](https://cloud.githubusercontent.com/assets/3496838/14117387/b2b9680c-f5a1-11e5-8726-373fc5908f9a.png)

**Comment by blakevanlan** [comment]
Sorry for the delayed response! Might be too late but in case anyone else comes across this.

After digging around in Mincer, I figured out what's causing your issue.

1. Files should be named with chained types with the left most extension being the end result. Your `main.less` file should actually be named `main.css.less`. See the [Mincer docs](https://github.com/nodeca/mincer#using-engines) for more info.
2. When specifying files for compiling, you should not include the path or additional extensions. Your parameter should instead be `connect-assets -i ... -c main.css` (after you've done rename above). 

Let me know if this works for you.

**Comment by blakevanlan** [comment]
Beefed up the description of compile on the CLI to hopefully help anyone who gets stuck on this in the future.
