### ISSUE TITLE
error in compileing bootstrap LESS

### ISSUE THREAD

**Issue by Amenocy** [adunkman/connect-assets#341]
hi 
there is an error  while compiling bootstrap last version 
[LessEngine] RuntimeError: No matching definition was found for `.pagination-size(10px, 16px, 18px, 1.3333333, 6px)` in /Users/Amin/expg/public/css/vendor/bootstrap/pagination.less:83:2

**Comment by blakevanlan** [comment]
Is it the 4.0.0-alpha.2 release that you're having problems with?

**Comment by Amenocy** [comment]
it seems problem in node changes and package manager . sorry
