### ISSUE TITLE
Update csswring dependency version

### ISSUE THREAD

**Issue by mozeryansky** [adunkman/connect-assets#343]
The current version of connect-assets depends on csswring v4.2.2, which is now at version 5.0.0. The version used by connect-assets contains deprecated dependencies.

**Comment by adunkman** [comment]
Sounds good to me — an excellent pull request opportunity! 👍

**Comment by mozeryansky** [comment]
I checked all the dependencies and updated them to their latest version and ran npm test to make sure.
The PR is #344
