### ISSUE TITLE
Sourcemaps for combined js file

### ISSUE THREAD

**Issue by codynguyen** [adunkman/connect-assets#345]
Hi,

We use Raygun.io for crash-reporting in production, and we found that without sourcemaps, the error details are not very helpful. I know connect-assets support source maps for seperate js files, but we are using a single combined js file in production, whose source look like this:

```javascript
// This is application.js
//
//= require semantic-ui
//= require highcharts/highcharts
//= require highcharts/modules/drilldown
//= require polyglot/build/polyglot
...
```

Is there anyway to generate a sourcemap file for the combined js? I'm thinking something like `application.js.map`?

Thanks a lot!

**Comment by blakevanlan** [comment]
We really should have better source map support for production environments. The focus of the source map support originally was for dev and staging kinds of use cases. I'll look into making it easy to use source maps for production (outputting for upload to external services and such). 

Thanks for the input!

**Comment by siboulet** [comment]
We badly need this to produce source maps suitable for debugging our production environment.

@blakevanlan can you share some of your thoughts on this feature?

**Comment by blakevanlan** [comment]
Finally had the time to take a look at this and I just published `5.3.0` that now has a `--sourceMaps` option for the CLI! This will write the source map for each file to the builtAssets directory with the `.map` extension appended to the original filename.

@codynguyen and @siboulet: Let me know how it works for you guys and if there's something I've missed. Sorry for the month delay on this one.

**Comment by blakevanlan** [comment]
From mincer:

> // Strange ")]}'\n" line added to sourcemap is for XSSI protection.
    // See spec for details.

And then found in the [Proposal for Source Map Revision 3](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?usp=sharing) at the bottom. Probably the right call is to make that an option as well.

**Comment by blakevanlan** [comment]
I'm going to leave this issue open until the XSSI protection is fixed. I'll add an option to remove the prefix when I get a chance.

**Comment by codynguyen** [comment]
@blakevanlan Oh I see, thanks for the info!

**Comment by codynguyen** [comment]
@blakevanlan I've created a PR over at https://github.com/nodeca/mincer/pull/227 to add the option to skip the XSSI protection header when writing source map to file. I can look at adding the corresponding option here when I got a respond from the mincer folks.

**Comment by puzrin** [comment]
I think it also worth ask Raygun stuff to fix sourcemaps support, as described in standard.

**Comment by codynguyen** [comment]
@puzrin I was gonna contact Raygun about that too, but then I realized XSSI protection header does not make sense if the source map file is NOT to be accessible via HTTP. In our case to keep the source map files private, we directly upload the files to Raygun's source map center and they then use those files internally to map the js backtrace to the original source.
