### ISSUE TITLE
Is this repo unmaintained?

### ISSUE THREAD

**Issue by aug-riedinger** [adunkman/connect-assets#351]
6 months without a commit... wondering ...

It still seems to me that this repo is the best asset management strategy in the nodejs platform.

Main reason to this is that I find dumb regenerating code on code change instead of when query happens, since the two events are not correlated:

**Risks when the query occurs faster than file regeneration**:
- risks of the asset not to be ready when the query occurs, generating error
- worse, risks that the process hasn't started yet and the older ressource is served, leading to even more confusion

**Cases of useless compilations**:
- On the other hand it happens pretty often to make several file changes/saves before testing the whole thing. Each regeneration **is** a waste.

I'd be glad to dive further into this repo if assistance is needed.

Best

**Comment by adunkman** [comment]
@aug-riedinger this issue really bummed me out to read this morning. You may want to consider the emotional impact of your issues before opening them in the future.

If this module works well for you, great! 

If you’d like to see changes or you find bugs, pull requests are always welcome!

**Comment by aug-riedinger** [comment]
Not sure I understand your comment. By emotional impact, you mean on you the maintainer or on me the author?

The overall activity on a repo is a very important decision maker in deciding whether to use it or not and even further, whether to contribute on it.

I'm still amazed that the asset-pipeline-rails-way of thinking did not take over the webpack/browserify approach. If you tell me that even you, the main author of this repo, gave up on connect assets and now use webpack, I'll give up for sure. Otherwise I'll have some steps to suggest to the roadmap for sure. :smile:
