### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by js-kyle** [adunkman/connect-assets#355]
Would you accept a PR for some improved CLI documentation?

I've been doing a big piece of work with this and needed to overcome a few issues where more documentation could have helped!

**Comment by blakevanlan** [comment]
Hi Kyle, I'd be happy to accept a PR with some improved CLI docs. Thanks!

**Comment by js-kyle** [comment]
Hey @blakevanlan I've added a PR for the improved docs.

Is there anything else I can add input to on this project etc? Happy to prepare some more PRs for work that will be merged.

Cheers

**Comment by blakevanlan** [comment]
Is there anything you found particularly lacking? Also, keep in mind that `mincer` really does the heavy lifting, connect-assets is fairly thin wrapper.

**Comment by js-kyle** [comment]
@blakevanlan  I was more thinking of any pressing bugs etc which could be good to fix
